name: Build and Deploy VectorStore to GHCR (master)
on:
  push:
    branches: [ master ]
env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: vectorstore
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: run docker compose
      run: docker compose up -d --wait vectorstore
    - name: just hit search_text
      run: |
        curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "the text is just a phony text", "top_k": 10}' http://localhost:8080/api/v1/search_text
    # - name: Log in to the Container registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./docker/vectorstore/Dockerfile
    #     push: true
    #     tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}
